import '@bsg/ui-styles/global.css';
import type {Metadata} from 'next'
import {Poppins} from 'next/font/google'

const poppins = Poppins({weight: '400', subsets: ['latin'], variable: '--poppins'})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={poppins.className}>
        <main className="flex flex-col items-center justify-center w-56 h-full">
            {children}
        </main>
        </body>
        </html>
    )
}
