apiVersion: apps/v1
kind: Deployment
metadata: 
  name: worker-deployment
  labels:
    app: leetcode-worker
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: leetcode-worker
  template:
    metadata: 
      labels:
        app: leetcode-worker
        
    spec:
      containers:
      - name: leetcode-worker
        image: "" # acmutd/bsg-frontend:latest  
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: worker-service
spec:
  selector:
    app: leetcode-worker
  ports: 
  - name: TCP
    port: 3001
    targetPort: 3001