import './globals.css'
import type {Metadata} from 'next'
import {Poppins} from 'next/font/google'
import Navbar from "@/components/customComponents/navbar"

const poppins = Poppins({weight: '400', subsets: ['latin'], variable: '--poppins'})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={poppins.className}>
        {/* Navbar should be outside main for correct layout */}
        <Navbar/>
        <main className="min-h-screen pt-[64px] flex flex-col items-center justify-center">
            {children}
        </main>
        </body>
        </html>
    )
}
