import '@bsg/ui-styles/global.css';
import type {Metadata} from 'next'
import {Poppins} from 'next/font/google'
import Navbar from "@bsg/components/navbar";

const poppins = Poppins({weight: '400', subsets: ['latin'], variable: '--poppins'})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={poppins.className}>
        <Navbar/>
        <main className="min-h-screen pt-[64px] flex flex-col items-center justify-center">
            {children}
            <div className="bg-red-500 text-white p-4">If this is styled, Tailwind is working</div>

        </main>
        </body>
        </html>
    )
}
